kind: Service
apiVersion: v1
metadata:
  name: nginxplus
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http-alt
  selector:
name: nginxplus-pods